- name: run the web server
  hosts: web_server_1
  become: true
  vars:
    files:
      - src: /home/ec2-user/ansible/Roman-Numerals-Converter/templates/phone.py
        dest: /etc/opt/
      - src: /home/ec2-user/ansible/Roman-Numerals-Converter/templates/index.html
        dest: /etc/opt/
      - src: /home/ec2-user/ansible/Roman-Numerals-Converter/templates/result.html
        dest: /etc/opt/
  tasks:
    - name: Installing python for python app
      ansible.builtin.yum:
        name:
          - python3
          - python3-pip
        state: present
        update_cache: yes

    - name: Install Python Flask dependencies
      pip:
        name: "{{ item }}"
        state: present
      with_items:
        - flask
        - flask-mysql

    - name: Copy files to folder
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop: "{{ files }}"

    - name: run flask app
      shell: |
        nohup python3 phone.py > log.txt 2>&1 &
